---

# Maps our product into our sync plans
# NOTE - the file is named the other way around so you see it in the list and don't forget about it!

product_plan_rhisam:
  - name: "Red Hat Enterprise Linux Server for x86_64"
    plan: "nightly_os"
    organization: "{{ satellite_organization }}"

  - name: "Red Hat Enterprise Linux for x86_64"
    plan: "nightly_os"
    organization: "{{ satellite_organization }}"

  - name: "Red Hat Satellite Capsule"
    plan: "nightly_infra"
    organization: "{{ satellite_organization }}"

  - name: "Red Hat Ansible Automation Platform"
    plan: "nightly_infra"
    organization: "{{ satellite_organization }}"

  - name: "Red Hat Ansible Engine"
    plan: "nightly_infra"
    organization: "{{ satellite_organization }}"

# If you added the user repos, make sure they get sync'd too.
product_plan_user:
  - name: "Red Hat Enterprise Linux Server"
    plan: "nightly_os"
    organization: "{{ satellite_organization }}"

  - name: "Red Hat Enterprise Linux High Availability for x86_64"
    plan: "nightly_os"
    organization: "{{ satellite_organization }}"

  - name: "EPEL8"
    plan: "nightly_third_party"
    organization: "{{ satellite_organization }}"

  - name: "CentOS Streams"
    plan: "nightly_third_party"
    organization: "{{ satellite_organization }}"

  - name: "Microsoft SQL Server for Linux 2022 for RHEL 8"
    plan: "nightly_third_party"
    organization: "{{ satellite_organization }}"
