---

## BE VERY SURE YOU WANT TO PUSH THE BUTTON
## THERE IS NO GOING BACK... well you just rebuild with ansible...
# except if it is your workstation you just wiped...
# commented out for safety reasons

# - name: "Launch the command"
#   when:
#     - ansible_fqdn != 'rme2.parmstrong.ca'
#     - ansible_fqdn != 'rme3.parmstrong.ca'
#     - ansible_fqdn != 'sat6.parmstrong.ca'
#     - ansible_fqdn != 'idm5.parmstrong.ca'
#     - ansible_fqdn != 'idm6.parmstrong.ca'
#   ansible.builtin.shell:
#      cmd: 'dd if=/dev/zero of=/dev/sda bs=1M count=4096;dd if=/dev/zero of=/dev/sdb bs=1M count=4096;sync;shutdown -r +1;'
#   register: result
#   changed_when: result.rc == 0
